### ISSUE TITLE
Example to run lexicator.py -p <word>

### ISSUE THREAD

**Issue by vladarta** [nyurik/lexicator#1]
Hi
I tried to run
```
python3 lexicator.py -p дом
```
and get
```
Traceback (most recent call last):
  File "lexicator.py", line 74, in <module>
    main(docopt(__doc__))
  File "lexicator.py", line 48, in main
    caches.wiki_words.get(words_to_do)
  File "/home/computer/Documents/projects/deepsage/python/lexicator/lexicator/wikicache/ContentStore.py", line 83, in get
    results = list(self.get_multiple([key], force))
  File "/home/computer/Documents/projects/deepsage/python/lexicator/lexicator/wikicache/ContentStore.py", line 99, in get_multiple
    keys_to_try = set(batch)
TypeError: unhashable type: 'list'
```

fix for it was to replace in lexicator/wikicache/ContentStore.py:99

```
keys_to_try = set(batch)   
```
with

```
keys_to_try = set()
for items in batch:
    for item in items:
        keys_to_try.add(item)
```

Please advise if I miss something with execution format

**Comment by nyurik** [comment]
Hi, sorry for delay, will look at it over the weekend  (are you still having this problem?)

**Comment by vladarta** [comment]
Hi, it is open source ;) Thank you for reply
for this issue fix from my comment worked for me, but I just wonder if where is another way to solve it

If it is possible, please pay more attention to    https://github.com/nyurik/lexicator/issues/2 - I was not able to make it work :-(
